"""Baked-in sample SOP/policy/training docs for the /admin/seed endpoint.
Swap these out for real documents via /admin/ingest once the pipeline is verified."""

SEED_DOCUMENTS = [
    {
        "title": "sop_warehouse_receiving",
        "doc_type": "sop",
        "content": "# SOP: Warehouse Receiving Process\n\n## Purpose\nThis procedure governs how inbound shipments are received, inspected, and logged\nat all company distribution centers.\n\n## Scope\nApplies to all warehouse associates, dock supervisors, and inventory control staff.\n\n## Procedure\n\n1. **Dock Assignment**: Upon truck arrival, the dock supervisor assigns a bay\n   number via the yard management system (YMS). Drivers must not be directed to\n   a bay verbally without a YMS confirmation.\n\n2. **Inspection**: Before unloading, the receiving associate performs a visual\n   seal check. If the seal number does not match the bill of lading (BOL),\n   escalate immediately to the Shift Supervisor and do NOT break the seal.\n\n3. **Unloading & Counting**: Pallets are unloaded and counted against the\n   packing list. Discrepancies of more than 2% of line-item quantity must be\n   logged as a \"Receiving Exception\" in the WMS within the same shift.\n\n4. **Damage Handling**: Any damaged units are set aside in the Damage Hold\n   area (Zone D). Photograph all damage before disposal or return processing.\n   Damage exceeding $500 estimated value requires Claims department sign-off\n   before further action.\n\n5. **Putaway**: Once counted and inspected, associates scan each pallet into\n   its assigned storage location. Putaway must be completed within 4 hours of\n   dock assignment for standard freight, or within 1 hour for temperature-\n   controlled freight.\n\n6. **Documentation**: The signed BOL, exception report (if any), and putaway\n   confirmation are uploaded to the WMS document repository before the\n   receiving record is closed.\n\n## Exceptions\nHazmat shipments follow SOP-HZ-002 instead of this document. Cross-dock\nshipments (no putaway) follow SOP-XD-004.\n\n## Related Documents\n- Policy: Warehouse Safety and PPE Requirements\n- Training Guide: Forklift Operation and Certification\n",
    },
    {
        "title": "policy_leave_and_attendance",
        "doc_type": "policy",
        "content": "# Policy: Leave and Attendance\n\n## Purpose\nDefines paid time off (PTO), sick leave, and attendance expectations for all\nhourly and salaried employees.\n\n## PTO Accrual\n- Warehouse and driver staff (hourly): accrue 1 hour of PTO for every 30 hours\n  worked, up to a maximum of 80 hours banked per calendar year.\n- Salaried staff: accrue PTO at a flat rate of 15 days per year, front-loaded\n  at the start of each calendar year.\n- Unused PTO above the cap does not roll over and is forfeited on Jan 1,\n  except where state law requires payout (check with HR for your state).\n\n## Sick Leave\nSick leave is separate from PTO and accrues at 1 hour per 40 hours worked for\nhourly employees, capped at 48 hours per year. No doctor's note is required\nfor absences of 2 days or fewer. Absences of 3+ consecutive days require a\nreturn-to-work note from a medical provider.\n\n## Attendance Points\n- A no-call/no-show results in 4 attendance points.\n- An unexcused late arrival (>10 minutes) results in 1 point.\n- Points expire on a rolling 90-day basis.\n- Accumulating 8 points in a rolling 90-day window triggers a documented\n  coaching conversation with your supervisor. 12 points triggers a formal\n  written warning per the Progressive Discipline Policy.\n\n## Requesting Time Off\nRequests must be submitted in the HR portal at least 5 business days in\nadvance for planned absences. Emergency/same-day absences must be reported\nby phone or text to your direct supervisor before your scheduled shift start.\n\n## Related Documents\n- Policy: Progressive Discipline\n- Training Guide: New Hire Orientation\n",
    },
    {
        "title": "training_forklift_safety",
        "doc_type": "training",
        "content": "# Training Guide: Forklift Operation and Certification\n\n## Who This Applies To\nAny associate who operates a powered industrial truck (forklift, order picker,\npallet jack with rider platform) in a company facility.\n\n## Certification Requirement\nOperators must complete both classroom training and a hands-on evaluation\nbefore operating any forklift unsupervised. Certification is valid for 3\nyears, and must be renewed earlier if the operator is involved in a\npreventable incident or switches to a different equipment class.\n\n## Pre-Shift Inspection Checklist\nBefore every shift, operators must complete the pre-shift checklist covering:\n- Tire condition and pressure\n- Forks: no visible cracks or bending\n- Hydraulic fluid leaks\n- Horn and backup alarm function\n- Seatbelt condition\n- Battery/fuel level\n\nAny failed item must be reported to the Shift Supervisor immediately, and the\nunit tagged \"Out of Service\" \u2014 it must not be operated until repaired.\n\n## Operating Rules\n- Maximum speed inside the warehouse is 5 mph, reduced to walking pace at\n  intersections and blind corners.\n- Loads must never exceed the rated capacity shown on the equipment data\n  plate.\n- Forks must be lowered fully and the parking brake engaged whenever the\n  operator dismounts, even briefly.\n- Pedestrians always have right of way; operators must make eye contact with\n  pedestrians before proceeding.\n\n## Incident Reporting\nAny collision, near-miss, or dropped load must be reported to the Shift\nSupervisor within 30 minutes, regardless of whether damage or injury\noccurred. A near-miss report does not result in disciplinary action and is\nused only for safety trend analysis.\n\n## Related Documents\n- SOP: Warehouse Receiving Process\n- Policy: Warehouse Safety and PPE Requirements\n",
    },
]
